spring:
  datasource:
    url: jdbc:mysql://148.70.237.65:3306/shop?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tempuser
    password: Tempuser12#$
